name: Docker Main Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: titlecardmaker-docker-main
  cancel-in-progress: true

jobs:
  docker-main:
    uses: ./.github/workflows/docker_build.yml
    with:
      tag: main
      source_sha: ${{ github.sha }}
      channel: main
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
