name: Docker Develop Release

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: titlecardmaker-docker-develop
  cancel-in-progress: true

jobs:
  docker-develop:
    uses: ./.github/workflows/docker_build.yml
    with:
      tag: develop
      source_sha: ${{ github.sha }}
      channel: develop
    secrets:
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
